[package]
name = "pocketvault-cli"
version = "0.1.5"
edition = "2021"

[[bin]]
name = "pocketvault-cli"
path = "src/main.rs"

[dependencies]
pocketvault-core = { path = "../pocketvault-core" }
clap = { version = "4", features = ["derive"] }
rpassword = "7"
shell-words = "1"
indicatif = "0.17"
owo-colors = "4"
ctrlc = "3"
dialoguer = "0.11"
console = "0.15"
ratatui = "0.29"
crossterm = "0.28"

[dev-dependencies]
tempfile = "3"
